name = "iat_simple_building"
author = "ItsATreee"
prefix = "iat"
mainprefix = "P"

[version]
path = "release_version.hpp"
git_hash = 0

[hemtt.release]
archive = false

[signing]
authority = "ItsATreeev2"